# Generated by Django 6.0.7 on 2026-07-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apis_metainfo", "0017_delete_uri"),
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IsMarriedTo",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "forename",
                    models.CharField(
                        blank=True, default="", max_length=4096, verbose_name="forename"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, default="", max_length=4096, verbose_name="surname"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, default="", max_length=4096, verbose_name="gender"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of death"
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "persons",
                "ordering": ["surname", "forename"],
                "abstract": False,
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
    ]
